### ISSUE TITLE
Textbook Versioning

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/web-components#190]
### Feature description

This feature gives the user the ability to change to a different version of the textbook, as well as view the change log to understand what has changed on the textbook. The designs are complete.

areas of change include:
- learn page versioning next to the "browse all content". this will scroll next to the "browse all content" down the page
- versioning will be available on the individual textbook pages on the left next to the "browse all content" 

https://www.figma.com/file/s94cmNVUcbFnTEbasdPNgN/1476-textbook-content-versioning?node-id=209%3A3177&t=rmG6WTM4svKq33JW-1

**Comment by techtolentino** [comment]
Since the MegaMenu dropdown is created in this Qiskit web-components package, I've transferred the feature request here.

Question for @gracelindsell or @frankharkins: What can the user expect when they select a different version?

For example: on the page, or in the dropdown menu... what should users see that is different when they choose v 1.0 versus v 2.1?

**Comment by techtolentino** [comment]
Closing this issue because I don't think this will be handled in the MegaMenu dropdown component anymore

(please re-open if I'm incorrect)
