### ISSUE TITLE
[Navigation UI] User Account text not showing up

### ISSUE THREAD

**Issue by mentesniker** [Qiskit/web-components#95]
### Steps to reproduce the problem

Resize the NavBar component until the navBar is collapsed. Then open the menu with the hamburguer button.

### What is the current behavior?

The text of the user account button is not displayed. Also the colors of the user icon and backgorund color are inverted (the first must be purple the second must be white).

### What is the expected behavior?

It should say "Account" and the colors should be inverted.

### Screenshots

![image](https://user-images.githubusercontent.com/35209340/170622084-0e5ac06e-5260-4358-9db3-94c64b9c49e6.png)

### Browser

Chrome

**Comment by y4izus** [comment]
Hey @mentesniker ! Thanks for submitting the issue! I've just checked this issue, but this is how I see the menu right now:

![Captura de pantalla 2023-01-24 a las 9 49 28](https://user-images.githubusercontent.com/17231966/214248139-15b0a6ae-1ec0-4473-9129-b1ce2e3ae18c.png)

Not sure if we are looking at different pages or if this issue is already fixed so please, could you check it again? And if it's already fixed, we can close it. Thank you!

**Comment by y4izus** [comment]
After reading this [comment](https://github.com/Qiskit/web-components/pull/94#issuecomment-1242160717), I can asume this issue is fixed, so I close it
